version: '3.8'

services: 
  postgresdb:
    image: postgres
    restart: unless-stopped
    env_file: ./.env
    environment:
     - POSTGRES_USER=$POSTGRESDB_USER
     - POSTGRES_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
     - POSTGRES_DB=$POSTGRESDB_DATABASE
    ports:
     - $POSTGRESDB_LOCAL_PORT:$POSTGRESDB_DOCKER_PORT
    volumes:
     - db:/var/lib/postgresql/
     - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
  app: 
    depends_on: 
     - postgresdb
    build: ./
    restart: unless-stopped
    env_file: ./.env
    ports:
    - $NODE_DOCKER_PORT:$PORT
    environment:
    - DB_HOST=$POSTGRESDB_HOST
    - DB_USER=$POSTGRESDB_USER
    - DB_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
    - DB_NAME=$POSTGRESDB_DATABASE
    - DB_PORT=$POSTGRESDB_DOCKER_PORT
    stdin_open: true
    tty: true


volumes:
  db:
